#
# Makefile for IIO Light sensors
#

GCOV_PROFILE := y

ccflags-y += -Werror
obj-$(CONFIG_ADJD_S311)		+= adjd_s311.o
obj-$(CONFIG_SENSORS_LM3533)	+= lm3533-als.o
obj-$(CONFIG_SENSORS_TSL2563)	+= tsl2563.o
obj-$(CONFIG_VCNL4000)		+= vcnl4000.o
